# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 17:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 2, 20, 45, 24, 168945)),
        ),
    ]
