# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 15:04
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_auto_20160302_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='id',
        ),
        migrations.RemoveField(
            model_name='note',
            name='note_text',
        ),
        migrations.RemoveField(
            model_name='note',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 3, 18, 4, 43, 975585)),
        ),
        migrations.AddField(
            model_name='note',
            name='favorites',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='note',
            name='uuid',
            field=models.CharField(default='', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notes.Category'),
        ),
    ]
