# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 15:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20160303_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 3, 18, 11, 12, 993164)),
        ),
    ]
