# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 15:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20160303_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 3, 18, 14, 27, 623046)),
        ),
    ]
