# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 15:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20160303_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
        migrations.AddField(
            model_name='note',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 3, 15, 55, 23, 328125, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='note',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
