# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20160304_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='header',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.TextField(),
        ),
    ]
