# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20160305_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
